/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ingeam' at '4/24/17 12:26 PM' with Gradle 2.14.1
 *
 * @author ingeam, @date 4/24/17 12:26 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
